In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, confusion_matrix

In [3]:
data=pd.read_csv("IMDb.csv")

In [4]:
my_cols=['castTotalLikes','directorLikes','actor1likes','movieLikes','fbPosters','year','duration','genre','contentRating','criticReviews','userReviews','userVotes','rating']
data=data[my_cols]
# to display top five rows from table.
data.head()

castTotalLikes  directorLikes  actor1likes  movieLikes  fbPosters    year  \
0            4834            0.0       1000.0       33000        0.0  2009.0   
1           48350          563.0      40000.0           0        0.0  2007.0   
2           11700            0.0      11000.0       85000        1.0  2015.0   
3          106759        22000.0      27000.0      164000        0.0  2012.0   
4             143          131.0        131.0           0        0.0     NaN   

   duration        genre contentRating  criticReviews  userReviews  userVotes  \
0     178.0       Action         PG-13          723.0       3054.0     886204   
1     169.0       Action         PG-13          302.0       1238.0     471220   
2     148.0       Action         PG-13          602.0        994.0     275868   
3     164.0       Action         PG-13          813.0       2701.0    1144337   
4       NaN  Documentary           NaN            NaN          NaN          8   

   rating  
0     7.9  
1     7.1  
2     6.8  
3     8.5  
4     7.1

In [5]:
from sklearn import preprocessing
Label = preprocessing.LabelEncoder()

data['genre']=Label.fit_transform(data['genre'])
data.head()

castTotalLikes  directorLikes  actor1likes  movieLikes  fbPosters    year  \
0            4834            0.0       1000.0       33000        0.0  2009.0   
1           48350          563.0      40000.0           0        0.0  2007.0   
2           11700            0.0      11000.0       85000        1.0  2015.0   
3          106759        22000.0      27000.0      164000        0.0  2012.0   
4             143          131.0        131.0           0        0.0     NaN   

   duration  genre contentRating  criticReviews  userReviews  userVotes  \
0     178.0      0         PG-13          723.0       3054.0     886204   
1     169.0      0         PG-13          302.0       1238.0     471220   
2     148.0      0         PG-13          602.0        994.0     275868   
3     164.0      0         PG-13          813.0       2701.0    1144337   
4       NaN      6           NaN            NaN          NaN          8   

   rating  
0     7.9  
1     7.1  
2     6.8  
3     8.5  
4     7.1

In [6]:
data['contentRating']=Label.fit_transform(data['contentRating'])
data.head()

castTotalLikes  directorLikes  actor1likes  movieLikes  fbPosters    year  \
0            4834            0.0       1000.0       33000        0.0  2009.0   
1           48350          563.0      40000.0           0        0.0  2007.0   
2           11700            0.0      11000.0       85000        1.0  2015.0   
3          106759        22000.0      27000.0      164000        0.0  2012.0   
4             143          131.0        131.0           0        0.0     NaN   

   duration  genre  contentRating  criticReviews  userReviews  userVotes  \
0     178.0      0              7          723.0       3054.0     886204   
1     169.0      0              7          302.0       1238.0     471220   
2     148.0      0              7          602.0        994.0     275868   
3     164.0      0              7          813.0       2701.0    1144337   
4       NaN      6             18            NaN          NaN          8   

   rating  
0     7.9  
1     7.1  
2     6.8  
3     8.5  
4     7.1

In [7]:
data=data.dropna()
data.describe().round(1)

castTotalLikes  directorLikes  actor1likes  movieLikes  fbPosters  \
count          4867.0         4867.0       4867.0      4867.0     4867.0   
mean           9944.3          696.1       6732.1      7648.0        1.4   
std           18420.6         2832.9      15232.4     19435.4        2.0   
min               0.0            0.0          0.0         0.0        0.0   
25%            1442.5            7.0        625.0         0.0        0.0   
50%            3151.0           50.0       1000.0       170.0        1.0   
75%           14165.0          199.5      11000.0      4000.0        2.0   
max          656730.0        23000.0     640000.0    349000.0       43.0   

         year  duration   genre  contentRating  criticReviews  userReviews  \
count  4867.0    4867.0  4867.0         4867.0         4867.0       4867.0   
mean   2002.4     108.3     4.1            8.1          143.0        279.0   
std      12.5      22.5     3.7            3.0          121.4        381.5   
min    1916.0      14.0     0.0            0.0            1.0          1.0   
25%    1999.0      94.0     1.0            7.0           53.0         69.0   
50%    2005.0     104.0     4.0            7.0          112.0        161.0   
75%    2011.0     118.0     7.0            9.0          197.0        334.5   
max    2016.0     330.0    20.0           18.0          813.0       5060.0   

       userVotes  rating  
count     4867.0  4867.0  
mean     85870.9     6.4  
std     140010.7     1.1  
min          5.0     1.6  
25%       9506.0     5.8  
50%      36108.0     6.5  
75%      99034.0     7.2  
max    1689764.0     9.3

In [8]:
data.corr().round(3)

castTotalLikes  directorLikes  actor1likes  movieLikes  \
castTotalLikes           1.000          0.118        0.951       0.209   
directorLikes            0.118          1.000        0.090       0.163   
actor1likes              0.951          0.090        1.000       0.135   
movieLikes               0.209          0.163        0.135       1.000   
fbPosters                0.096         -0.041        0.076       0.011   
year                     0.114         -0.062        0.090       0.223   
duration                 0.120          0.173        0.082       0.214   
genre                   -0.090         -0.008       -0.064      -0.075   
contentRating           -0.039         -0.027       -0.020      -0.053   
criticReviews            0.259          0.181        0.186       0.688   
userReviews              0.202          0.221        0.142       0.397   
userVotes                0.262          0.297        0.189       0.535   
rating                   0.095          0.173        0.085       0.256   

                fbPosters   year  duration  genre  contentRating  \
castTotalLikes      0.096  0.114     0.120 -0.090         -0.039   
directorLikes      -0.041 -0.062     0.173 -0.008         -0.027   
actor1likes         0.076  0.090     0.082 -0.064         -0.020   
movieLikes          0.011  0.223     0.214 -0.075         -0.053   
fbPosters           1.000  0.060     0.029 -0.062          0.013   
year                0.060  1.000    -0.132 -0.039          0.189   
duration            0.029 -0.132     1.000 -0.075         -0.062   
genre              -0.062 -0.039    -0.075  1.000          0.153   
contentRating       0.013  0.189    -0.062  0.153          1.000   
criticReviews      -0.030  0.280     0.251 -0.087         -0.124   
userReviews        -0.068  0.000     0.352 -0.081         -0.086   
userVotes          -0.026  0.012     0.339 -0.133         -0.094   
rating             -0.066 -0.212     0.350 -0.003         -0.004   

                criticReviews  userReviews  userVotes  rating  
castTotalLikes          0.259        0.202      0.262   0.095  
directorLikes           0.181        0.221      0.297   0.173  
actor1likes             0.186        0.142      0.189   0.085  
movieLikes              0.688        0.397      0.535   0.256  
fbPosters              -0.030       -0.068     -0.026  -0.066  
year                    0.280        0.000      0.012  -0.212  
duration                0.251        0.352      0.339   0.350  
genre                  -0.087       -0.081     -0.133  -0.003  
contentRating          -0.124       -0.086     -0.094  -0.004  
criticReviews           1.000        0.605      0.622   0.333  
userReviews             0.605        1.000      0.797   0.309  
userVotes               0.622        0.797      1.000   0.432  
rating                  0.333        0.309      0.432   1.000

In [9]:
train,test = train_test_split(data,random_state=42)
X_train = train[train.columns[2:30]]
y_train = train['genre']
X_test = test[test.columns[2:30]]
y_test = test['genre']

In [10]:
scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [11]:
from sklearn.neural_network import MLPClassifier
MLP = MLPClassifier(hidden_layer_sizes=(10,10,10),max_iter=1000)
MLP.fit(X_train,y_train.values.ravel())

MLPClassifier(hidden_layer_sizes=(10, 10, 10), max_iter=1000)

In [13]:
predictions = MLP.predict(X_test)
predictions

array([0, 5, 4, ..., 7, 7, 4])

In [14]:
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

[[278   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 120   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0  11   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0  61   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0 305   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0  78   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0  18   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0 242   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0  10   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0  70   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   1   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   1   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   8   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   1   0   0   0   0]
 [  0 

C:\Users\Monisha\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Monisha\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Monisha\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
